package Vista.Paneles;

import Controladores.metodosGaussControlador;

/**
 *
 * @author ariellugo92
 */
public class pnlResultado1 extends javax.swing.JPanel {

    metodosGaussControlador mgc = new metodosGaussControlador();
    
    public pnlResultado1() {
        initComponents();
    }

    private float arr_nums[][];
    private int num_incog;

    // metodo para mostrar la matriz ampliada
    public void setCalcularMatrizAmpliada(float[][] arr_numeros, int num_incognitas) {
        this.arr_nums = arr_numeros;
        this.num_incog = num_incognitas;
        
        this.txtMatrizResult.setText(mgc.getMatrizAmpliada(arr_nums, num_incog));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMatrizResult = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtMatrizResult.setColumns(20);
        txtMatrizResult.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtMatrizResult.setRows(5);
        jScrollPane2.setViewportView(txtMatrizResult);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMatrizResult;
    // End of variables declaration//GEN-END:variables
}
