package Vista.Paneles;

import Controladores.metodosGaussControlador;

/**
 *
 * @author ariellugo
 */
public class pnlResultado4 extends javax.swing.JPanel {

    metodosGaussControlador mgc = new metodosGaussControlador();
    
    public pnlResultado4() {
        initComponents();
    }
    
    public void setMostrarResultados(float [][] matriz_orig, float [] incognitas, int tam){
        String texto = mgc.getTextoComprobado(matriz_orig, incognitas, tam);
        this.txtComprobando.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComprobando = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtComprobando.setColumns(20);
        txtComprobando.setRows(5);
        jScrollPane1.setViewportView(txtComprobando);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtComprobando;
    // End of variables declaration//GEN-END:variables
}
