package Vista.Paneles;

import Controladores.metodosGaussControlador;
import Pojos.TransformacionElemental;
import Vista.frmGauss;

/**
 *
 * @author ariellugo92
 */
public class pnlResultado2 extends javax.swing.JPanel {

    metodosGaussControlador mgc = new metodosGaussControlador();
    public frmGauss frmPadre;
    
    public pnlResultado2() {
        initComponents();
    }
    
    public void setFrmPadre(frmGauss frm){
        this.frmPadre = frm;
    }
    
    public void setTransfomacionesElementales(float [][] arr_nums, int num_incog){
        TransformacionElemental te = mgc.getTransformacionesElementales(arr_nums, num_incog);
        txtTransformaciones.setText(te.getTexto());
        this.frmPadre.setMatrizResultTransform(te.getMatriz());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTransformaciones = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtTransformaciones.setColumns(20);
        txtTransformaciones.setRows(5);
        jScrollPane2.setViewportView(txtTransformaciones);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtTransformaciones;
    // End of variables declaration//GEN-END:variables
}
